dev-cobiodiv-organisms
PnX-SI/GeoNature-atlas pull request #330
Opened 2021-08-05 12:47 UTC by corentinlange

Ajout des pages organismes.

AJout des organismes participants aux observations sur les fiches espèces.

2021-08-05 15:09 UTC, Adrien-Pajot requested changes
atlas/templates/organismSheet/topSpecie.html

transform it in 

topSpecies.html

2021-08-05 15:24 UTC, Adrien-Pajot requested changes
Pareil

data/observations_mailles.sql

Attention à ce qu'on pousse, restons génériques. 
Le drop n'a rien à faire ici. 
Pourquoi la VUE t_mailles_territoires est ici? Elle est ailleurs normalement ? 

Pour la transfo dans vm_observations maille en 2154 tu peux la garder

2021-08-05 15:52 UTC, corentinlange commented
> data/gn2/atlas_synthese.sql
> 
> T'es sûr qu'on pousse ça ? On doit laisser synthèse eff comme elle est non ? 

Je me pose une question par rapport à ça, est est-ce qu'on développe pour un futur master ou on se coupe pour faire un format de plus grande envergure : beaucoup de données et grand territoire ?

2021-08-06 07:03 UTC, Adrien-Pajot commented
Je pense qu'on peut faire un hybride. 
Soit tu fais un script qui contient les deux versions (anciennes et nouvelles) soit tu fais deux scripts et dans les noms on s'y retrouve. @TheoLechemia , @camillemonchicourt , @bouttier ?

2021-08-06 08:19 UTC, corentinlange commented
Le dernier commit rajoute les derniers ajouts sur la branch dev-cobiodiv.

2021-08-06 08:43 UTC, camillemonchicourt commented
Salut. Je n'ai pas vu les modifications de la VM mais on ne peut pas faire une VM qui fonctionne dans tous les cas ?

2021-08-06 08:51 UTC, jpm-cbna reviewed
Il faut clarifier l'utilisation de t_subdivided_territory. Soit on la garde pour l'utiliser dans la vm l_communes, soit il faut la supprimer.

2021-08-06 08:51 UTC, jpm-cbna commented on data/migrate_subdivided_territory.sql
> +BEGIN;
Et la migration pour la VM vm_organismes ? Je ne la voie pas.

2021-08-06 08:51 UTC, jpm-cbna commented on data/observations_mailles.sql
> +CREATE VIEW ref_geo.mon_territoire AS
C'est pas un peu trop spécifique à Cobiodiv ?

2021-08-06 08:51 UTC, jpm-cbna commented on .gitignore
> +<<<<<<< HEAD
Je pense qu'il y a du code d'un diff qui a été commité ici ...

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/app.py
> +
Ces 3 lignes vides ne me semblent pas vraiment utile.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/atlasRoutes.py
> +    vmOrganismesRepository,
Il me semble qu'il faudrait avoir tous les termes en anglais dans le code ("organism" plutôt qu'"organisme", par exemple).

Ce commentaire est valable pour tous les autres fichiers de cette PR...

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/static/main.js
> +        configuration.URL_APPLICATION + "/static/custom/glossaire.json",
Pourquoir le mettre en français ? Il faut faire un choix entre français et anglais...

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/core/navbar.html
> +    var language = '{{ '/' + CURRENT_LANGUAGE }}';
Les espace en fin de ligne sont inutiles.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/core/navbar.html
> +    var language = ''
Les espaces en fin de ligne sont inutiles.
Par contre, on peut rajouter un point virgule à la fin de la ligne 8.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/home/_main.html
> +
Cette ligne vide est inutle.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/organismSheet/_main.html
> +<link rel="stylesheet" href="{{ url_for('static', filename='css/ficheEspece.css') }}" />
Il faudrait indenter ces lignes.
Il est vraiment plus clair de considérer les lignes "{% ...%}" comme si c'était des balises HTML et donc de les indenter de la même façon que le HTML.
Les lignes 52 à 67 sont bien indentées.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/organismSheet/blocInfos.html
> +
Supprimer cette ligne vide.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/organismSheet/identityCard.html
> +
Supprimer ces 2 lignes vides.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/organismSheet/mapObs.html
> +            </div>
Désindenter d'un cran ces lignes.
La ligne 9 vide peut être supprimée.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/organismSheet/statsInfos.html
> +    </row>
Il faudrait régler le niveau d'indentation des fichiers HTML à 2 ou 4 espaces via un fichier .editorconfig.
Ici, il y a un mélange entre indentation de 2 et 4 espaces.

2021-08-06 08:51 UTC, jpm-cbna commented on atlas/templates/specieSheet/otherInformations.html
> +                    </a></li>
Si possible, mettre la balise "a" sur sa propre ligne et l’indentant. Même chose pour son contenu.

2021-08-06 08:51 UTC, jpm-cbna commented on data/gn2/atlas_ref_geo.sql
> +CREATE MATERIALIZED VIEW atlas.t_subdivided_territory
Si l'on ajoute cette VM, il faut l'utiliser...
Plutôt que de restreindre les obs au territoire dans la vm_observations, nous pourrions reduire les communes au territoire dans la vm l_communes...
Sinon, il faut supprimer toutes les références à t_subdivided_territory dans tout le code de cette PR...

2021-08-06 08:51 UTC, jpm-cbna commented on data/observations_mailles.sql
> +CREATE MATERIALIZED VIEW atlas.t_mailles_territoire
Je ne voie aucune suppression dans un autre fichier de "atlas.t_mailles_territoire". Cela ne fait pas doublon du coup  dans ce fichier ? Elle n'est pas créé dans un autre fichier ?

2021-08-06 08:58 UTC, corentinlange commented on .gitignore
> +<<<<<<< HEAD
Corrigé !

2021-08-06 09:00 UTC, corentinlange commented on data/observations_mailles.sql
> +CREATE MATERIALIZED VIEW atlas.t_mailles_territoire
Corrigé

2021-08-06 09:01 UTC, corentinlange commented on atlas/templates/organismSheet/blocInfos.html
> +
Corrigé

2021-08-06 09:01 UTC, corentinlange commented on atlas/templates/organismSheet/identityCard.html
> +
Corrigé

2021-08-06 09:02 UTC, corentinlange commented on atlas/templates/organismSheet/mapObs.html
> +            </div>
Corrigé

2021-08-06 09:13 UTC, corentinlange commented on atlas/templates/organismSheet/mapObs.html
> +            </div>
Corrigé

2021-08-06 09:32 UTC, jpm-cbna commented
> on ne peut pas faire une VM qui fonctionne dans tous les cas ?

Le changements concernent:
- la vm "vm_observations" où l'on ne limite plus les observations à leur présence sur le territoire
- la vue "syntheseff" où l'on ne floute plus les données en fonction du niveau de diffusion ou de la sensibilité, ni ne supprime les observations de type "absence" ou avec un niveau de diffusion "4" (= ne pas diffuser).

Concernant la limitation au niveau du territoire, il est envisageable (à tester) de la basculer au niveau de la vm l_communes qui liste les communes du territoire. En effet, la vue syntheseff joint les observations aux communes de la vm l_communes.

Concernant la vue "syntheseff", il me semble nécessaire de garder la suppression des observations avec niveau de de diffusion "4" ou de type "absence". C'est ce que je fais au niveau des SINP et cela fonctionne.
Concernant le floutage, il serait intéressant de l'activer uniquement si l'Atlas affiche les observations aux points. Dans le cas, de l'affichage par maille, c'est moins grave si ce n'est pas maintenu... 
Je me demande aussi s'il ne serait pas plus intéressant de flouter la géométrie dans la vm vm_observations plutôt que dans la vue "syntheseff". Cela prendrait juste un peu plus de temps au niveau du rafraichissement de la VM "vm_observations"...

2021-08-06 13:23 UTC, corentinlange commented on data/update_vm_observations.sql
> +DROP MATERIALIZED VIEW IF EXISTS atlas.t_subdivided_territory;
Ajouté !

2021-08-06 13:23 UTC, corentinlange commented on atlas/templates/specieSheet/otherInformations.html
> +                    </a></li>
Corrigé

2021-08-06 13:23 UTC, corentinlange commented on data/gn2/atlas_ref_geo.sql
> +CREATE MATERIALIZED VIEW atlas.t_subdivided_territory
Voir dans une prochaine PR

2021-08-06 13:25 UTC, corentinlange commented on data/atlas.sql
> +create MATERIALIZED VIEW atlas.vm_organismes
Corrigé !

2021-08-06 13:26 UTC, corentinlange commented on atlas/templates/organismSheet/statsInfos.html
> +    </row>
A voir dans une prochaine PR

2021-08-06 13:32 UTC, corentinlange commented on data/update_vm_observations.sql
> -    m.the_geom,
Corrigé !

2021-08-06 13:34 UTC, Adrien-Pajot approved these changes
Attention, la vm_observations dans le fichier atlas.sql a légèrement changé entre ta version et celle d'avant et notamment : 
s.the_geom_point::geometry('POINT', 3857) est devenu s.the_geom_point LIGNE 30

et 

le geojson n'est plus transformé 

et 

le deuxième JOIN a été supprimé 

Je crois pas qu'on doive le pousser ici, ou alors tu as corrigé un bug ?

2021-08-06 13:39 UTC, Adrien-Pajot approved these changes
Dans le fichier update_vm_observations.sql :

ton update de vm_observations est différent de l'ancien, normal ?

2021-08-06 13:48 UTC, corentinlange commented
Retour sur les scripts SQL de la branch develop effectué.
Les créations pour les organismes restent présents.

2021-08-06 13:49 UTC, corentinlange commented
> Dans le fichier update_vm_observations.sql :
> 
> ton update de vm_observations est différent de l'ancien, normal ?

Je viens de remettre l'ancien, voir la prochaine PR qui se concentre sur les scripts SQLs

2021-08-06 13:49 UTC, corentinlange commented
> Attention, la vm_observations dans le fichier atlas.sql a légèrement changé entre ta version et celle d'avant et notamment :
> s.the_geom_point::geometry('POINT', 3857) est devenu s.the_geom_point LIGNE 30
> 
> et
> 
> le geojson n'est plus transformé
> 
> et
> 
> le deuxième JOIN a été supprimé
> 
> Je crois pas qu'on doive le pousser ici, ou alors tu as corrigé un bug ?

Version d'avant remise, voir la prochaine PR qui se concentre sur les scripts SQLs

2021-08-09 08:29 UTC, merged