feat: add personal data link in footer
PnX-SI/GeoNature-atlas pull request #574
Opened 2024-09-26 08:44 UTC by juggler31

2024-09-26 10:31 UTC, camillemonchicourt approved these changes

2024-09-26 10:31 UTC, camillemonchicourt commented on atlas/configuration/config.py.example
> +# Afficher le lien "données personnelle" dans le footer
```suggestion
# Afficher le lien "données personnelles" dans le footer
```

2024-09-26 13:28 UTC, juggler31 commented on atlas/configuration/config.py.example
> +# Afficher le lien "données personnelle" dans le footer
Corrigé, merci

2024-09-27 07:06 UTC, marcantoinedupre requested changes
C'est globalement bon pour moi :+1: 

Je t'ai fait quelques remarques mineures. Pour les deux remarques qui concernent du code supprimé je pense qu'il peut être pertinent de le faire dans deux commits séparés avec une brêve explication dans les messages de commit. À toi de voir. :)

2024-09-27 10:01 UTC, juggler31 commented on atlas/configuration/config_schema.py
> +    AFFICHAGE_RGPD = fields.Boolean(load_default=False)
@camillemonchicourt tu valides le fait de ne pas afficher le lien et la modale par défaut afin de ne pas provoquer de "Breaking Change" sur les instances existantes ? Sachant que c'est censé être obligatoire en France !

2024-09-27 12:06 UTC, camillemonchicourt commented on atlas/configuration/config_schema.py
> +    AFFICHAGE_RGPD = fields.Boolean(load_default=False)
Il y a 2 approches :
- soit on l'affiche pas par défaut et on l'indique bien dans le changelog en suggérant de le compléter et l'activer, mais certains risquent de passer à côté de l'info et encore plus ceux qui installent GNA plus tard
- soit on l'active par défaut et on l'indique clairement aussi dans le changelog et certains passeront à côté de l'info et auront un RGPD avec des valeurs par défaut sans s'en rendre compte.

Aucune n'est parfaite mais je penche plus pour la seconde pour donner de la visibilité à cette nouvelle fonctionnalité.

2024-09-30 09:15 UTC, juggler31 commented on atlas/configuration/config_schema.py
> +    AFFICHAGE_RGPD = fields.Boolean(load_default=False)
Comme parlé ensemble, nous avons choisi je mettre la modal avec le texte par défaut pour tout le monde et qu'il soit désactivable dans la configuration.

2024-10-01 14:59 UTC, submarcos commented
il manquerait pas un changelog pour expliquer ? ou une doc

2024-10-11 16:48 UTC, merged